create database E_Commerce
use E_Commerce

create table Users(
	id varchar(5) primary key,
	username varchar(50),
	password varchar(50),
	customer_name varchar(max),
	email varchar(max),
	phone varchar(20),
	address1 varchar(100),
	address2 varchar(100),
	address3 varchar(100),
)

create table Category(
	id varchar(10) primary key,
	display varchar(50),
)

create table Product(
	id varchar(10) primary key,
	title nvarchar(100),
	id_cate varchar(10),
	categorySlug varchar(max),
	image1 varchar(max),
	image2 varchar(max),
	price int,
	slug varchar(100),
	colors varchar(100),
	size varchar(50),
	descriptions nvarchar(max)

	FOREIGN KEY (id_cate) REFERENCES Category(id)
)

create table Cart(
	id varchar(9) primary key,
	customer_id varchar(5),
	create_date smalldatetime,
	total int,

	FOREIGN KEY (customer_id) REFERENCES Users(id)
)

create table CartInfo(
	cart_id varchar(9),
	product_id varchar(10),
	amount int

	primary key (cart_id, product_id),
	foreign key (cart_id) references Cart(id),
	foreign key (product_id) references Product(id)
)

insert into Category values ('erq200113r', 'ao thun');
insert into Category values ('erqj9r5tw2', 'ao somi');
insert into Category values ('erq231146o', 'ao len');
insert into Category values ('erq55122d1', 'quan kaki');
insert into Category values ('erq135r5to', 'quan jean');
insert into Category values ('rqt6yu748o', 'phu kien')

insert into Product values ('trwyhnbd47', 'ao thun nam', 'erq200113r','ao-thun','null', 'null', '900000', 'null', 'xanh', 'M', 'lalalalla')
insert into Product values ('74516ffssg', 'ao thun nu', 'erq200113r','ao-thun','null', 'null', '900000', 'null', 'do', 'M,X', 'lalalalla')
insert into Product values ('tf6234ytfa', 'quan thun nam', 'erq135r5to','quan-thun','null', 'null', '900000', 'null', 'tim', 'S', 'lalalalla')
insert into Product values ('67234cccas', 'quan kaki nam', 'erq55122d1','quan-kaki','null', 'null', '900000', 'null', 'vang', 'XL', 'lalalalla')
insert into Product values ('awsdg52345', 'ao len', 'erq231146o','ao-len' ,'null','null', '900000', 'null', 'den', 'S', 'lalalalla')
insert into Product values ('asd5567111', 'vong tay go', 'rqt6yu748o', 'phu-kien','null','null', '1400000', 'null', 'xanh', '', 'memememe')
insert into Product values ('asc623ggg1', 'nhan deo', 'rqt6yu748o','phu-kien' ,'null','null', '5600000', 'null', 'do', '', 'memememe')

insert into Product values ('x1e19t4ucd',N'Áo thun cổ tròn Dinasour','erq200113r','ao-thun','images/aothuncotrondinasour-1.png','images/aothuncotrondinasour-2.png',230000,'ao-thun-co-tron-dinasour','orange,yellow,red','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('3p91mxalbr',N'Áo thun cổ tròn Dinasour 2','erq200113r','ao-thun','images/aothuncotrondinasour2-1.png','images/aothuncotrondinasour2-2.png',230000,'ao-thun-co-tron-dinasour2','orange,yellow,blue','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('7kzjz3ngsj',N'Áo thun cổ tròn Dinasour 3','erq200113r','ao-thun','images/aothuncotrondinasour3-1.png','images/aothuncotrondinasour3-2.png',230000,'ao-thun-co-tron-dinasour3','orange,brown,blue','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('z1lfoenif2',N'Áo thun cổ tròn Oh baby','erq200113r','ao-thun','images/aothuncotronohbaby-1.png','images/aothuncotronohbaby-2.png',200000,'ao-thun-co-tron-ohbaby','white,brown,pink','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('m34iogqrpa',N'Áo thun trơn ngắn tay','erq200113r','ao-thun','images/aothuntronngantay-1.png','images/aothuntronngantay-2.png',190000,'ao-thun-tron-ngan-tay','pink,purple','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('ahmzn40hgq',N'Áo thun basic','erq200113r','ao-thun','images/aothunbasic-1.png','images/aothunbasic-2.png',160000,'ao-thun-basic','black,white,blue,red,pink,purple','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('0lp1m2ksaj',N'Áo thun cổ tròn tay ngắn','erq200113r','ao-thun','images/aothuncotrontayngan-1.png','images/aothuncotrontayngan-2.png',200000,'ao-thun-co-tron-tay-ngan','blue,yellow','M,L,XL,XXL',N'Nhóm thiết kế tại Paris, do Christophe Lemaire dẫn đầu, đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Áo thun cổ thuyền có thiết kế đơn giản được làm từ chất liệu vải jersey dày dặn.Do chất liệu áo độc đáo với số lượng sợi thấp được dệt nhỏ gọn nên sản phẩm bền, lâu phai và càng giặt càng đẹp.Cổ áo có thể điều chỉnh để tạo kiểu cổ phẳng.Dáng áo vừa vặn, rộng rãi mang phong cách hiện đại.')
insert into Product values ('rwil4wankv',N'Áo thun cổ tròn dáng rộng','erq200113r','ao-thun','images/aothuncotrondangrong-1.png','images/aothuncotrondangrong-2.png',240000,'ao-thun-co-tron-dang-rong','red,white,blue,gray','XS,M,L,XL,XXL',N'Đội ngũ thiết kế ở Paris do Christophe Lemaire đứng đầu đã tạo ra bộ sưu tập LifeWear mới bằng cách sử dụng các loại vải tân tiến và kiểu dáng hiện đại.Một sản phẩm có cảm giác mềm mại khô ráo, và có thể sử dụng để mặc thường ngày và trang trọng.Thiết kế cổ tròn với cổ áo ôm sát hơn là điểm mấu chốt của thiết kế.')
insert into Product values ('87uc30o7ym',N'Áo thun Dry cổ tròn ngắn tay','erq200113r','ao-thun','images/aothundrycotronngantay-1.png','images/aothundrycotronngantay-2.png',140000,'ao-thun-dry-co-tron-ngan-tay','red,white,blue,orange,yellow','XS,M,L,XL,XXL',N'Công nghệ làm khô nhanh giúp món đồ này nhanh khô ngay cả khi đổ mồ hôi hoặc giặt.Có thể tự mặc hoặc mặc như đồ lót bên trong nhờ đường viền cổ áo và tổng thể vừa vặn.')
insert into Product values ('63ih5l2220',N'Áo thun cổ tròn dài tay','erq200113r','ao-thun','images/aothuncotrondaitay-1.png','images/aothuncotrondaitay-2.png',250000,'ao-thun-co-tron-dai-tay','red,white,black,blue','XS,M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('ee9oxpfdvy',N'Áo Polo Dry-Ex Ngắn Tay','erq200113r','ao-thun','images/aothunpolodryngantay-1.png','images/aothunpolodryngantay-2.png',190000,'ao-thun-polo-dry-ngan-tay','red,white,black,blue','XS,M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('zi4clxc3ye',N'Áo Thun Dáng Rộng Cổ Tròn Có Túi Tay Lỡ','erq200113r','ao-thun','images/aothuncotrontaylo-1.png','images/aothuncotrontaylo-2.png',290000,'ao-thun-polo-dry-ngan-tay','yellow,white,black,blue','XS,M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('u8dbl35h02',N'Áo Polo Vải Pique Co Giãn Ngắn Tay','erq200113r','ao-thun','images/aothunpolopigquengantay-1.png','images/aothunpolopigquengantay-2.png',190000,'ao-thun-polo-pigque-ngan-tay','pink,white,yellow,black','XS,M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('u8w5fy1pv5',N'Áo Cardigan Extra Fine Merino Cổ V Dài Tay','erq231146o','ao-len','images/aolencargadianextradaitay-1.png','images/aolencargadianextradaitay-1.png',690000,'ao-len-cargadian-extra-dai-tay','black,brown','M,L,XL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('brclfgmxj5',N'Áo Len Extra Fine Merino Cổ V Dài Tay','erq231146o','ao-len','images/aolenextradaitay-1.png','images/aolenextradaitay-2.png',590000,'ao-len-extra-dai-tay','black,blue,red','M,L,XL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('nbmemap00h',N'Áo Sơ Mi Extra Fine Cotton Ngắn Tay','erqj9r5tw2','ao-somi','images/aosomiextrangantay-1.png','images/aosomiextrangantay-2.png',200000,'ao-somi-extra-ngan-tay','white,blue,red','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('7wptuwtrle',N'Áo Sơ Mi Vải Modal Cotton Cổ Mở Ngắn Tay','erqj9r5tw2','ao-somi','images/aosomimodal-1.png','images/aosomimodal-2.png',250000,'ao-somi-modal-ngan-tay','white,blue,brown','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('6djexd0fwf',N'Áo Sơ Mi Extra Fine Cotton Cổ Trụ Dài Tay','erqj9r5tw2','ao-somi','images/aosomiextradaitay-1.png','images/aosomiextradaitay-2.png',320000,'ao-somi-extra-dai-tay','white,blue','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('sq8dkgudyx',N'Áo Sơ Mi Extra Fine Cotton Twill Dáng Rộng Dài Tay','erqj9r5tw2','ao-somi','images/aosomiextradangrongdaitay-1.png','images/aosomiextradangrongdaitay-2.png',370000,'ao-somi-extra-dang-rong-dai-tay','white,blue','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('u1w8d8vozz',N'Áo Sơ Mi kẻ Caro','erqj9r5tw2','ao-somi','images/aosomikecaro-1.png','images/aosomikecaro-2.png',320000,'ao-somi-ke-caro','white,blue,green','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('cccbfwpjh0',N'Áo Sơ Mi Casual','erqj9r5tw2','ao-somi','images/aosomicasual-1.png','images/aosomicasual-2.png',340000,'ao-casual','white,blue,green','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('bgy48wozo4',N'Áo Sơ Mi Sành điệu','erqj9r5tw2','ao-somi','images/aosomisanhdieu-1.png','images/aosomisanhdieu-2.png',320000,'ao-casual','white,blue,green','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('bopia1c0ag',N'Quần Jeans Siêu Co Giãn Skinny Fit','erq135r5to','quan-jean','images/quanjeansieucodan-1.png','images/quanjeansieucodan-2.png',370000,'quan-jean-sieu-co-gian','black,blue','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('rjhmw7n16e',N'Quần Jeans Slim Fit','erq135r5to','quan-jean','images/quanjeanslimfit-1.png','images/quanjeanslimfit-2.png',370000,'quan-jean-slim-fit','black,blue','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('801c2tig89',N'Quần Jean Ống Suông Dáng Regular Fit','erq135r5to','quan-jean','images/quanjeanongsuong-1.png','images/quanjeanongsuong-2.png',420000,'quan-jean-ong-suong','blue','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('le6my4rdxm',N'Quần Jean Crop fit','erq135r5to','quan-jean','images/quanjeancropfit-1.png','images/quanjeancropfit-2.png',420000,'quan-jean-crop-fit','blue,gray','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('tnuqv6wom2',N'Quần Jean Skinny fit','erq135r5to','quan-jean','images/quanjeanskinnyfit-1.png','images/quanjeanskinnyfit-2.png',450000,'quan-jean-skinny-fit','blue,black','M,L,XL,XXL',N'Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('sh22m714mj',N'Quần Jean Trơn','erq135r5to','quan-jean','images/quanjeantron-1.png','images/quanjeantron-2.png',450000,'quan-jean-tron','blue,black','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('6vpjzt8aj0',N'Quần Kaki LƯNG V.SLIMCROP ','erq55122d1','quan-kaki','images/quankakislimcropv-1.png','images/quankakislimcropv-2.png',410000,'quan-kaki-slim-crop-v','brown,white','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('gxq01dysry',N'Quần Kaki STRAIGHT CROP FORM ','erq55122d1','quan-kaki','images/quankakistraightcropform-1.png','images/quankakistraightcropform-2.png',460000,'quan-kaki-straigth-crop-form','brown,black','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('yindafdf53',N'Quần Kaki WIDE LEG FORM','erq55122d1','quan-kaki','images/quankakiwideleg-1.png','images/quankakiwideleg-2.png',440000,'quan-kaki-wide-leg','brown','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('zoe8ey2a39',N'Quần Kaki SLIM','erq55122d1','quan-kaki','images/quankakislim-1.png','images/quankakislim-2.png',420000,'quan-kaki-slim','brown,white,black','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('ctrpbencxf',N'Quần Kaki Baggy Casual','erq55122d1','quan-kaki','images/quankakibaggycasual-1.png','images/quankakibaggycasual-2.png',390000,'quan-kaki-baggy-casual','brown,white,black','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('vhtxsxt5uu',N'Quần Kaki Ống Suông','erq55122d1','quan-kaki','images/quankakiongsuong-1.png','images/quankakiongsuong-2.png',390000,'quan-kaki-ong-suong','brown,white,black','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')
insert into Product values ('hhjx5iyqcj',N'Quần Kaki Công sở','erq55122d1','quan-kaki','images/quankakicongso-1.png','images/quankakicongso-1.png',390000,'quan-kaki-cong-so','brown,white,black','M,L,XL,XXL',N'Được thiết kế cho mọi lứa tuổi.Cạp cao vừa tạo cảm giác vừa vặn an toàn và thoải mái.Túi trước và túi sau được đặt cao, và mặt sau của quần được vát xéo để tôn lên đường nét của đôi chân bạn.Dễ mặc ngay cả với kiểu xắn gấu.Đã áp dụng quy trình xử lý đặc biệt để tạo cảm giác sờn rách khác biệt và sử dụng phương pháp nhuộm không đều được phát triển bởi Kaihara để tạo độ sâu như vải denim cổ điển.Được sản xuất với phương pháp giặt tiết kiệm nước nước do Trung Tâm Cải Tiến Jeans phát triển độc lập, giúp giảm hơn 90% lượng nước sử dụng tại thời điểm xử lý vải trong sản xuất.Chất liệu bao gồm 13,5-oz. denim dệt bằng 100% cotton Kaihara giúp tạo một cấu trúc vải mềm mại vừa phải.Chất lượng cao và giá trị lớn so với giá cả.Có sẵn những màu phổ biến nhất của chúng tôi.Màu sắc mới được thêm vào để làm thêm phong phú thêm phong cách của bạn.')





